INSERT INTO TRABALLADOR (NAME_USER_TRABALLADOR, APELIDO1_TRABALLADOR, APELIDO2_TRABALLADOR, PWD_TRABALLADOR, EMAIL_TRABALLADOR) 
VALUES ('Juan', 'Pérez', 'García', 'contraseña123', 'juan.perez@gmail.com');

INSERT INTO TRABALLADOR (NAME_USER_TRABALLADOR, APELIDO1_TRABALLADOR, APELIDO2_TRABALLADOR, PWD_TRABALLADOR, EMAIL_TRABALLADOR) 
VALUES ('María', 'Rodríguez', 'López', 'password456', 'maria.rodriguez@yahoo.com');

INSERT INTO TRABALLADOR (NAME_USER_TRABALLADOR, APELIDO1_TRABALLADOR, APELIDO2_TRABALLADOR, PWD_TRABALLADOR, EMAIL_TRABALLADOR) 
VALUES ('Pedro', 'Martínez', 'Núñez', 'clave789', 'pedro.martinez@hotmail.com');

INSERT INTO TRABALLADOR (NAME_USER_TRABALLADOR, APELIDO1_TRABALLADOR, APELIDO2_TRABALLADOR, PWD_TRABALLADOR, EMAIL_TRABALLADOR) 
VALUES ('Lucía', 'Fernández', 'Santos', 'lucia_2025', 'lucia.fernandez@outlook.com');

INSERT INTO TRABALLADOR (NAME_USER_TRABALLADOR, APELIDO1_TRABALLADOR, APELIDO2_TRABALLADOR, PWD_TRABALLADOR, EMAIL_TRABALLADOR) 
VALUES ('Carlos', 'Gómez', 'Ruiz', 'segura12', 'carlos.gomez@icloud.com');

INSERT INTO TRABALLADOR (NAME_USER_TRABALLADOR, APELIDO1_TRABALLADOR, APELIDO2_TRABALLADOR, PWD_TRABALLADOR, EMAIL_TRABALLADOR) 
VALUES ('Ana', 'Castro', 'Morales', 'ana12345', 'ana.castro@gmail.com');

INSERT INTO TRABALLADOR (NAME_USER_TRABALLADOR, APELIDO1_TRABALLADOR, APELIDO2_TRABALLADOR, PWD_TRABALLADOR, EMAIL_TRABALLADOR) 
VALUES ('Luis', 'Ramírez', 'Alonso', 'luis001', 'luis.ramirez@gmail.com');

INSERT INTO TRABALLADOR (NAME_USER_TRABALLADOR, APELIDO1_TRABALLADOR, APELIDO2_TRABALLADOR, PWD_TRABALLADOR, EMAIL_TRABALLADOR) 
VALUES ('Carmen', 'Hernández', 'Díaz', 'secure_pass', 'carmen.hernandez@gmail.com');

INSERT INTO TRABALLADOR (NAME_USER_TRABALLADOR, APELIDO1_TRABALLADOR, APELIDO2_TRABALLADOR, PWD_TRABALLADOR, EMAIL_TRABALLADOR) 
VALUES ('Roberto', 'Vega', 'Álvarez', 'roberto_88', 'roberto.vega@gmail.com');

INSERT INTO TRABALLADOR (NAME_USER_TRABALLADOR, APELIDO1_TRABALLADOR, APELIDO2_TRABALLADOR, PWD_TRABALLADOR, EMAIL_TRABALLADOR) 
VALUES ('Elena', 'Sánchez', 'Prieto', 'elena_pwd', 'elena.sanchez@gmail.com');

