INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Mancuernas', 'COD001', 'Mancuernas ajustables de acero', 10, 50, 'Pesas', 25);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Esterilla de yoga', 'COD002', 'Esterilla antideslizante de 6 mm', 1.5, 20, 'Accesorios de yoga', 40);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Bicicleta estática', 'COD003', 'Bicicleta de spinning profesional', 25, 350, 'Cardio', 10);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Cuerda para saltar', 'COD004', 'Cuerda de velocidad ajustable', 0.3, 15, 'Cardio', 60);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Balón medicinal', 'COD005', 'Balón de ejercicio de 5 kg', 5, 40, 'Entrenamiento funcional', 20);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Máquina de remo', 'COD006', 'Remo ergonómico con resistencia ajustable', 30, 500, 'Cardio', 5);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Kettlebell', 'COD007', 'Kettlebell de 12 kg', 12, 35, 'Pesas', 30);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Cinta de correr', 'COD008', 'Cinta de correr eléctrica plegable', 50, 700, 'Cardio', 8);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Banco de pesas', 'COD009', 'Banco ajustable para entrenamiento', 15, 100, 'Pesas', 12);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Chaleco lastrado', 'COD010', 'Chaleco con peso de 10 kg', 10, 45, 'Entrenamiento funcional', 15);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Rueda abdominal', 'COD011', 'Rueda doble con agarres ergonómicos', 1.2, 25, 'Accesorios', 35);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Set de bandas elásticas', 'COD012', 'Bandas de resistencia de varios niveles', 0.8, 30, 'Accesorios', 50);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Fitball', 'COD013', 'Pelota de ejercicio de 65 cm', 1.1, 20, 'Entrenamiento funcional', 25);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Rodillera deportiva', 'COD014', 'Rodillera ajustable para protección', 0.2, 18, 'Protección', 100);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Guantes de gimnasio', 'COD015', 'Guantes de entrenamiento con agarre', 0.3, 15, 'Accesorios', 70);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Step aeróbico', 'COD016', 'Plataforma ajustable para step', 8, 45, 'Cardio', 20);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Elíptica', 'COD017', 'Máquina elíptica con monitor', 40, 600, 'Cardio', 6);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Botella de agua', 'COD018', 'Botella reutilizable de acero inoxidable', 0.4, 12, 'Accesorios', 150);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Discos de peso', 'COD019', 'Set de discos de 2.5 kg', 5, 30, 'Pesas', 50);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) VALUES ('Pulseras de sudor', 'COD020', 'Pulseras absorbentes de algodón', 0.1, 8, 'Accesorios', 200);
INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) 
VALUES ('Auriculares Bluetooth', 'COD021', 'Auriculares inalámbricos con tecnología Bluetooth', 0.25, 40, 'Accesorios', 30);

INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) 
VALUES ('Mesa para pesas', 'COD022', 'Mesa ajustable para almacenamiento de pesas', 20, 60, 'Pesas', 15);

INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) 
VALUES ('Bandas elásticas', 'COD023', 'Set de bandas elásticas para entrenamiento de resistencia', 0.5, 30, 'Accesorios', 50);

INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) 
VALUES ('Reloj deportivo', 'COD024', 'Reloj con monitor de frecuencia cardíaca y GPS', 0.3, 100, 'Accesorios', 25);

INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) 
VALUES ('Botella de acero', 'COD025', 'Botella térmica de acero inoxidable, 500 ml', 0.4, 12, 'Accesorios', 120);

INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) 
VALUES ('Tobilleras', 'COD026', 'Tobilleras ajustables con peso para entrenamiento', 1, 15, 'Entrenamiento funcional', 40);

INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) 
VALUES ('Kit para yoga', 'COD027', 'Kit completo para yoga, incluye esterilla, bloques y correa', 2, 50, 'Accesorios de yoga', 20);

INSERT INTO PRODUCTO (NOME_PRODUCTO, CODIGO_PRODUCTO, DESCRIPCION_PRODUCTO, PESO_PRODUCTO, PRECIO_PRODUCTO, TIPO_PRODUCTO, STOCK_PRODUCTO) 
VALUES ('Cojín lumbar', 'COD028', 'Cojín ergonómico para soporte lumbar', 0.6, 25, 'Accesorios', 50);
